[versions]
agp = "8.13.2"
kotlin = "2.2.21"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.12.1"
composeBom = "2025.12.00"

daggerHiltVersion = "2.57.2"
daggerHiltNavigationComposeVersion = "1.3.0"
navigationVersion = "2.9.6"
coroutinesVersion = "1.10.2"
lifecycleVersion = "2.10.0"
dataStoreVersion = "1.2.0"
roomVersion = "2.8.4"
lottieVersion = "6.7.1"
kspVersion = "2.2.20-2.0.2"
yChartVersion = "2.1.0"
vicoVersion = "1.14.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }

# Dagger Hilt
daggerHilt = { group = "com.google.dagger" , name = "hilt-android" , version.ref = "daggerHiltVersion" }
daggerHilt-navigation-compose = { group = "androidx.hilt" ,name  = "hilt-navigation-compose" , version.ref = "daggerHiltNavigationComposeVersion"}
daggerHiltCompiler = { group = "com.google.dagger" , name = "hilt-compiler" , version.ref = "daggerHiltVersion" }

# Navigation
navigation = { group = "androidx.navigation" , name = "navigation-compose" , version.ref = "navigationVersion" }

# Coroutines & lifecycle
kotlinCoroutines = { group = "org.jetbrains.kotlinx" , name = "kotlinx-coroutines-android" , version.ref = "coroutinesVersion" }
viewModel = { group = "androidx.lifecycle" , name = "lifecycle-viewmodel-ktx" , version.ref = "lifecycleVersion" }
viewModelForCompose = { group = "androidx.lifecycle" , name = "lifecycle-viewmodel-compose" , version.ref = "lifecycleVersion" }
lifecycleCompose = { group = "androidx.lifecycle" , name = "lifecycle-runtime-compose" , version.ref = "lifecycleVersion" }
savedState = { group = "androidx.lifecycle" , name = "lifecycle-viewmodel-savedstate" , version.ref = "lifecycleVersion" }

# DataStore
androidx-dataStore = { group = "androidx.datastore" , name  = "datastore-preferences" , version.ref = "dataStoreVersion" }

# Room SQLite
roomSqlite = { group = "androidx.room" , name = "room-runtime" , version.ref = "roomVersion" }
roomCoroutinesSupport = { group = "androidx.room" , name = "room-ktx" , version.ref = "roomVersion" }
roomCompiler = { group = "androidx.room" , name = "room-compiler" , version.ref = "roomVersion" }
androidx-room-common = { group = "androidx.room", name = "room-common", version.ref = "roomVersion" }

# Lottie animations
lottieanimations = {group = "com.airbnb.android",name = "lottie-compose",version.ref = "lottieVersion"}

#  Ychart
yChart = { group = "co.yml" , name = "ycharts" , version.ref = "yChartVersion" }

#  Vico chart
vicoCompose = { group = "com.patrykandpatrick.vico" , name = "compose" , version.ref = "vicoVersion" }
vicoComposeM3 = { group = "com.patrykandpatrick.vico" , name = "compose-m3" , version.ref = "vicoVersion" }
vico = { group = "com.patrykandpatrick.vico" , name = "core" , version.ref = "vicoVersion" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

daggerHiltPlugin = { id = "com.google.dagger.hilt.android" , version.ref = "daggerHiltVersion" }
kspPlugin = { id = "com.google.devtools.ksp" , version.ref = "kspVersion" }